version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app  
    networks:
      - backend-network
    env_file:
      - .env

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app  
    depends_on:
      - db  
    networks:
      - backend-network
    env_file:
      - .env

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=user  
      - POSTGRES_PASSWORD=password  
      - POSTGRES_DB=audiovault  
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge

volumes:
  postgres_data: 
